In [ ]:
import matplotlib.pyplot as plt 
import sympy 
import numpy as np


In [2]:
for i in range(1,6):
    print(i,": ",i**2)

1 :  1
2 :  4
3 :  9
4 :  16
5 :  25


In [1]:
import sympy
for i in range(1,6):
    if not sympy.isprime(i):
        print(i,": ",i**2)


1 :  1
4 :  16


In [2]:
squares=[i**2 for i in range(1,6)]
for i, i2 in enumerate(squares):
    print(i,": ",i2)

0 :  1
1 :  4
2 :  9
3 :  16
4 :  25


In [4]:
psquares=[i**2 for i in range(1,6) if not sympy.isprime(i)]
print(psquares)

[1, 16]


In [6]:
import numpy as np

In [8]:
#Matrix Multiplication
X=np.array([[1,2],[3,4],[5,6]])
Y=np.array([[7,8,9,1],[1,2,3,4]])
C=np.matmul(X,Y)                    #np.dot(X,Y) or A@B
print(C)

[[ 9 12 15  9]
 [25 32 39 19]
 [41 52 63 29]]


In [10]:
#element wise multiplication
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[3,2],[5,4],[3,1]])
print(A*B)                          

[[ 3  4]
 [15 16]
 [15  6]]


In [16]:
rand_array = np.random.randint(0,10,(5,7)) 
print(rand_array[2:5,0:2])

[[5 5]
 [1 5]
 [2 2]]


In [23]:
import cv2 as cv
im=cv.imread(r'./images/gal_gaussian.png')
blur=cv.GaussianBlur(im,(6,6),0)

cv.namedWindow('Image',cv.WINDOW_AUTOSIZE)
cv.imshow('Image',im)
cv.waitKey(0)
cv.imshow('Image',blur)
cv.waitKey(0)
cv.destroyAllWindows()
